// Code generated by "stringer -type ASTUnaryOperation -trimprefix ASTUnary -output ast_unary_operation_string.go ast.go"; DO NOT EDIT.

package gazebo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASTUnaryNegate-1]
	_ = x[ASTUnaryNot-2]
}

const _ASTUnaryOperation_name = "NegateNot"

var _ASTUnaryOperation_index = [...]uint8{0, 6, 9}

func (i ASTUnaryOperation) String() string {
	i -= 1
	if i < 0 || i >= ASTUnaryOperation(len(_ASTUnaryOperation_index)-1) {
		return "ASTUnaryOperation(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ASTUnaryOperation_name[_ASTUnaryOperation_index[i]:_ASTUnaryOperation_index[i+1]]
}
