// Code generated by "stringer -type ASTBinaryOperation -trimprefix ASTBinary -output ast_binary_operation_string.go ast.go"; DO NOT EDIT.

package gazebo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ASTBinaryAdd-1]
	_ = x[ASTBinarySubtract-2]
	_ = x[ASTBinaryMultiply-3]
	_ = x[ASTBinaryDivide-4]
	_ = x[ASTBinaryModulus-5]
	_ = x[ASTBinaryEqual-6]
	_ = x[ASTBinaryNotEqual-7]
	_ = x[ASTBinaryLess-8]
	_ = x[ASTBinaryLessEqual-9]
	_ = x[ASTBinaryGreater-10]
	_ = x[ASTBinaryGreaterEqual-11]
	_ = x[ASTBinaryAnd-12]
	_ = x[ASTBinaryOr-13]
}

const _ASTBinaryOperation_name = "AddSubtractMultiplyDivideModulusEqualNotEqualLessLessEqualGreaterGreaterEqualAndOr"

var _ASTBinaryOperation_index = [...]uint8{0, 3, 11, 19, 25, 32, 37, 45, 49, 58, 65, 77, 80, 82}

func (i ASTBinaryOperation) String() string {
	i -= 1
	if i < 0 || i >= ASTBinaryOperation(len(_ASTBinaryOperation_index)-1) {
		return "ASTBinaryOperation(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ASTBinaryOperation_name[_ASTBinaryOperation_index[i]:_ASTBinaryOperation_index[i+1]]
}
