package main

import (
	"flag"
	"fmt"

	"github.com/johnfrankmorgan/gazebo/compiler"
	"github.com/johnfrankmorgan/gazebo/parser"
	"github.com/johnfrankmorgan/gazebo/vm"
	"github.com/niemeyer/pretty"
)

var config struct {
	dump struct {
		ast      bool
		bytecode bool
	}
}

func main() {
	flag.BoolVar(&config.dump.ast, "A", true, "Dump out the AST")
	flag.BoolVar(&config.dump.bytecode, "B", true, "Dump out the generated bytecode")
	flag.Parse()

	program := flag.Args()[0]
	parser := parser.New(parser.Tokenize(program))

	tree := parser.Parse()
	if config.dump.ast {
		fmt.Println("AST")
		pretty.Printf("%# v\n\n", tree)
	}

	bytecode := compiler.New().Compile(tree)
	if config.dump.bytecode {
		fmt.Println("BYTECODE")
		for i, ins := range bytecode {
			fmt.Printf("0x%04x :: [0x%02x] %24s :: %v\n", i, int(ins.Op), ins.Op, ins.Arg)
		}
		fmt.Println()
	}

	ret := vm.New().Run(bytecode)
	pretty.Printf("%# v\n", ret)
}
