// Code generated by "stringer -type=opcode"; DO NOT EDIT.

package gazebo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opInvalid-0]
	_ = x[opPrint-1]
	_ = x[opDump-2]
	_ = x[opExecChild-3]
	_ = x[opLoadConst-4]
	_ = x[opLoadNull-5]
	_ = x[opLoadTrue-6]
	_ = x[opLoadFalse-7]
	_ = x[opLoadName-8]
	_ = x[opStoreName-9]
	_ = x[opJump-10]
	_ = x[opRelJump-11]
	_ = x[opRelJumpIfTrue-12]
	_ = x[opRelJumpIfFalse-13]
	_ = x[opReturn-14]
	_ = x[opReturnNull-15]
	_ = x[opUnNegate-16]
	_ = x[opUnNot-17]
	_ = x[opBinAnd-18]
	_ = x[opBinOr-19]
	_ = x[opBinEqual-20]
	_ = x[opBinNotEqual-21]
	_ = x[opBinLess-22]
	_ = x[opBinLessEqual-23]
	_ = x[opBinGreater-24]
	_ = x[opBinGreaterEqual-25]
	_ = x[opBinAdd-26]
	_ = x[opBinSub-27]
	_ = x[opBinMul-28]
	_ = x[opBinDiv-29]
	_ = x[opBinMod-30]
}

const _opcode_name = "opInvalidopPrintopDumpopExecChildopLoadConstopLoadNullopLoadTrueopLoadFalseopLoadNameopStoreNameopJumpopRelJumpopRelJumpIfTrueopRelJumpIfFalseopReturnopReturnNullopUnNegateopUnNotopBinAndopBinOropBinEqualopBinNotEqualopBinLessopBinLessEqualopBinGreateropBinGreaterEqualopBinAddopBinSubopBinMulopBinDivopBinMod"

var _opcode_index = [...]uint16{0, 9, 16, 22, 33, 44, 54, 64, 75, 85, 96, 102, 111, 126, 142, 150, 162, 172, 179, 187, 194, 204, 217, 226, 240, 252, 269, 277, 285, 293, 301, 309}

func (i opcode) String() string {
	if i < 0 || i >= opcode(len(_opcode_index)-1) {
		return "opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opcode_name[_opcode_index[i]:_opcode_index[i+1]]
}
