// Code generated by "stringer -type=Op"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoadConst-1]
	_ = x[StoreName-2]
	_ = x[LoadName-3]
	_ = x[Jump-4]
	_ = x[RelJumpIfTrue-5]
	_ = x[RelJumpIfFalse-6]
	_ = x[RelJump-7]
	_ = x[BinEq-8]
	_ = x[BinNEq-9]
	_ = x[BinAdd-10]
	_ = x[BinSub-11]
	_ = x[BinMul-12]
	_ = x[BinDiv-13]
	_ = x[BinLess-14]
	_ = x[BinLessEq-15]
	_ = x[BinGreater-16]
	_ = x[BinGreaterEq-17]
	_ = x[MakeFunction-18]
	_ = x[Return-19]
	_ = x[Call-20]
	_ = x[AttrGet-21]
}

const _Op_name = "LoadConstStoreNameLoadNameJumpRelJumpIfTrueRelJumpIfFalseRelJumpBinEqBinNEqBinAddBinSubBinMulBinDivBinLessBinLessEqBinGreaterBinGreaterEqMakeFunctionReturnCallAttrGet"

var _Op_index = [...]uint8{0, 9, 18, 26, 30, 43, 57, 64, 69, 75, 81, 87, 93, 99, 106, 115, 125, 137, 149, 155, 159, 166}

func (i Op) String() string {
	i -= 1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
