// Code generated by "stringer -type=Op"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoadConst-1]
	_ = x[StoreName-2]
	_ = x[LoadName-3]
	_ = x[Jump-4]
	_ = x[RelJumpIfTrue-5]
	_ = x[RelJumpIfFalse-6]
	_ = x[RelJump-7]
	_ = x[BinAdd-8]
	_ = x[BinSub-9]
	_ = x[BinMul-10]
	_ = x[BinDiv-11]
}

const _Op_name = "LoadConstStoreNameLoadNameJumpRelJumpIfTrueRelJumpIfFalseRelJumpBinAddBinSubBinMulBinDiv"

var _Op_index = [...]uint8{0, 9, 18, 26, 30, 43, 57, 64, 70, 76, 82, 88}

func (i Op) String() string {
	i -= 1
	if i < 0 || i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
