// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExecuteChild-1]
	_ = x[LoadConstant-2]
	_ = x[LoadNull-3]
	_ = x[LoadFalse-4]
	_ = x[LoadTrue-5]
	_ = x[LoadName-6]
	_ = x[StoreName-7]
	_ = x[MakeFunc-8]
	_ = x[Jump-9]
	_ = x[RelativeJump-10]
	_ = x[RelativeJumpIfTrue-11]
	_ = x[RelativeJumpIfFalse-12]
	_ = x[UnaryNegate-13]
	_ = x[UnaryInvert-14]
	_ = x[BinaryAnd-15]
	_ = x[BinaryOr-16]
	_ = x[BinaryEqual-17]
	_ = x[BinaryNotEqual-18]
	_ = x[BinaryLess-19]
	_ = x[BinaryLessOrEqual-20]
	_ = x[BinaryGreater-21]
	_ = x[BinaryGreaterOrEqual-22]
	_ = x[BinaryAdd-23]
	_ = x[BinarySubtract-24]
	_ = x[BinaryMultiply-25]
	_ = x[BinaryDivide-26]
	_ = x[BinaryModulus-27]
	_ = x[Call-28]
	_ = x[Return-29]
}

const _Opcode_name = "ExecuteChildLoadConstantLoadNullLoadFalseLoadTrueLoadNameStoreNameMakeFuncJumpRelativeJumpRelativeJumpIfTrueRelativeJumpIfFalseUnaryNegateUnaryInvertBinaryAndBinaryOrBinaryEqualBinaryNotEqualBinaryLessBinaryLessOrEqualBinaryGreaterBinaryGreaterOrEqualBinaryAddBinarySubtractBinaryMultiplyBinaryDivideBinaryModulusCallReturn"

var _Opcode_index = [...]uint16{0, 12, 24, 32, 41, 49, 57, 66, 74, 78, 90, 108, 127, 138, 149, 158, 166, 177, 191, 201, 218, 231, 251, 260, 274, 288, 300, 313, 317, 323}

func (i Opcode) String() string {
	i -= 1
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
