// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExecuteChild-1]
	_ = x[LoadConstant-2]
	_ = x[LoadNull-3]
	_ = x[LoadFalse-4]
	_ = x[LoadTrue-5]
	_ = x[LoadName-6]
	_ = x[StoreName-7]
	_ = x[Jump-8]
	_ = x[RelativeJump-9]
	_ = x[RelativeJumpIfTrue-10]
	_ = x[RelativeJumpIfFalse-11]
	_ = x[UnaryNegate-12]
	_ = x[UnaryNot-13]
	_ = x[BinaryAnd-14]
	_ = x[BinaryOr-15]
	_ = x[BinaryEqual-16]
	_ = x[BinaryNotEqual-17]
	_ = x[BinaryLess-18]
	_ = x[BinaryLessOrEqual-19]
	_ = x[BinaryGreater-20]
	_ = x[BinaryGreaterOrEqual-21]
	_ = x[BinaryAdd-22]
	_ = x[BinarySubtract-23]
	_ = x[BinaryMultiply-24]
	_ = x[BinaryDivide-25]
	_ = x[BinaryModulus-26]
}

const _Opcode_name = "ExecuteChildLoadConstantLoadNullLoadFalseLoadTrueLoadNameStoreNameJumpRelativeJumpRelativeJumpIfTrueRelativeJumpIfFalseUnaryNegateUnaryNotBinaryAndBinaryOrBinaryEqualBinaryNotEqualBinaryLessBinaryLessOrEqualBinaryGreaterBinaryGreaterOrEqualBinaryAddBinarySubtractBinaryMultiplyBinaryDivideBinaryModulus"

var _Opcode_index = [...]uint16{0, 12, 24, 32, 41, 49, 57, 66, 70, 82, 100, 119, 130, 138, 147, 155, 166, 180, 190, 207, 220, 240, 249, 263, 277, 289, 302}

func (i Opcode) String() string {
	i -= 1
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
