// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package op

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExecuteChild-1]
	_ = x[LoadConstant-2]
	_ = x[LoadNull-3]
	_ = x[LoadFalse-4]
	_ = x[LoadTrue-5]
	_ = x[LoadName-6]
	_ = x[StoreName-7]
	_ = x[MakeFunc-8]
	_ = x[Jump-9]
	_ = x[RelativeJump-10]
	_ = x[RelativeJumpIfTrue-11]
	_ = x[RelativeJumpIfFalse-12]
	_ = x[GetAttribute-13]
	_ = x[UnaryNegate-14]
	_ = x[UnaryInvert-15]
	_ = x[BinaryAnd-16]
	_ = x[BinaryOr-17]
	_ = x[BinaryEqual-18]
	_ = x[BinaryNotEqual-19]
	_ = x[BinaryLess-20]
	_ = x[BinaryLessOrEqual-21]
	_ = x[BinaryGreater-22]
	_ = x[BinaryGreaterOrEqual-23]
	_ = x[BinaryAdd-24]
	_ = x[BinarySubtract-25]
	_ = x[BinaryMultiply-26]
	_ = x[BinaryDivide-27]
	_ = x[BinaryModulus-28]
	_ = x[Call-29]
	_ = x[Return-30]
}

const _Opcode_name = "ExecuteChildLoadConstantLoadNullLoadFalseLoadTrueLoadNameStoreNameMakeFuncJumpRelativeJumpRelativeJumpIfTrueRelativeJumpIfFalseGetAttributeUnaryNegateUnaryInvertBinaryAndBinaryOrBinaryEqualBinaryNotEqualBinaryLessBinaryLessOrEqualBinaryGreaterBinaryGreaterOrEqualBinaryAddBinarySubtractBinaryMultiplyBinaryDivideBinaryModulusCallReturn"

var _Opcode_index = [...]uint16{0, 12, 24, 32, 41, 49, 57, 66, 74, 78, 90, 108, 127, 139, 150, 161, 170, 178, 189, 203, 213, 230, 243, 263, 272, 286, 300, 312, 325, 329, 335}

func (i Opcode) String() string {
	i -= 1
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
