// Code generated by "stringer -type=BinaryOp -trimprefix=BinaryOp"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinaryOpAnd-1]
	_ = x[BinaryOpOr-2]
	_ = x[BinaryOpEqual-3]
	_ = x[BinaryOpNotEqual-4]
	_ = x[BinaryOpLess-5]
	_ = x[BinaryOpLessOrEqual-6]
	_ = x[BinaryOpGreater-7]
	_ = x[BinaryOpGreaterOrEqual-8]
	_ = x[BinaryOpAdd-9]
	_ = x[BinaryOpSubtract-10]
	_ = x[BinaryOpMultiply-11]
	_ = x[BinaryOpDivide-12]
	_ = x[BinaryOpModulus-13]
}

const _BinaryOp_name = "AndOrEqualNotEqualLessLessOrEqualGreaterGreaterOrEqualAddSubtractMultiplyDivideModulus"

var _BinaryOp_index = [...]uint8{0, 3, 5, 10, 18, 22, 33, 40, 54, 57, 65, 73, 79, 86}

func (i BinaryOp) String() string {
	i -= 1
	if i < 0 || i >= BinaryOp(len(_BinaryOp_index)-1) {
		return "BinaryOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BinaryOp_name[_BinaryOp_index[i]:_BinaryOp_index[i+1]]
}
