// Code generated by "stringer -type=BinOp"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinOpAdd-1]
	_ = x[BinOpSub-2]
	_ = x[BinOpMul-3]
	_ = x[BinOpDiv-4]
	_ = x[BinOpEq-5]
	_ = x[BinOpNEq-6]
	_ = x[BinOpGreater-7]
	_ = x[BinOpGreaterEq-8]
	_ = x[BinOpLess-9]
	_ = x[BinOpLessEq-10]
}

const _BinOp_name = "BinOpAddBinOpSubBinOpMulBinOpDivBinOpEqBinOpNEqBinOpGreaterBinOpGreaterEqBinOpLessBinOpLessEq"

var _BinOp_index = [...]uint8{0, 8, 16, 24, 32, 39, 47, 59, 73, 82, 93}

func (i BinOp) String() string {
	i -= 1
	if i < 0 || i >= BinOp(len(_BinOp_index)-1) {
		return "BinOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BinOp_name[_BinOp_index[i]:_BinOp_index[i+1]]
}
