// Code generated by "stringer -type=LitType"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LitTypeIdent-1]
	_ = x[LitTypeNumber-2]
	_ = x[LitTypeString-3]
}

const _LitType_name = "LitTypeIdentLitTypeNumberLitTypeString"

var _LitType_index = [...]uint8{0, 12, 25, 38}

func (i LitType) String() string {
	i -= 1
	if i < 0 || i >= LitType(len(_LitType_index)-1) {
		return "LitType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LitType_name[_LitType_index[i]:_LitType_index[i+1]]
}
