// Code generated by "stringer -type=UnaryOp -trimprefix=UnaryOp"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnaryOpNegate-1]
	_ = x[UnaryOpInvert-2]
}

const _UnaryOp_name = "NegateInvert"

var _UnaryOp_index = [...]uint8{0, 6, 12}

func (i UnaryOp) String() string {
	i -= 1
	if i < 0 || i >= UnaryOp(len(_UnaryOp_index)-1) {
		return "UnaryOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UnaryOp_name[_UnaryOp_index[i]:_UnaryOp_index[i+1]]
}
