// Code generated by "stringer -type=TKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TEOF-1]
	_ = x[TComment-2]
	_ = x[TWhitespace-3]
	_ = x[TParenOpen-4]
	_ = x[TParenClose-5]
	_ = x[TBraceOpen-6]
	_ = x[TBraceClose-7]
	_ = x[TDot-8]
	_ = x[TComma-9]
	_ = x[TSemicolon-10]
	_ = x[TBang-11]
	_ = x[TEqual-12]
	_ = x[TEqualEqual-13]
	_ = x[TBangEqual-14]
	_ = x[TLess-15]
	_ = x[TLessEqual-16]
	_ = x[TGreater-17]
	_ = x[TGreaterEqual-18]
	_ = x[TPlus-19]
	_ = x[TMinus-20]
	_ = x[TStar-21]
	_ = x[TSlash-22]
	_ = x[TNumber-23]
	_ = x[TIdent-24]
	_ = x[TIf-25]
	_ = x[TElse-26]
	_ = x[TWhile-27]
	_ = x[TReturn-28]
}

const _TKind_name = "TEOFTCommentTWhitespaceTParenOpenTParenCloseTBraceOpenTBraceCloseTDotTCommaTSemicolonTBangTEqualTEqualEqualTBangEqualTLessTLessEqualTGreaterTGreaterEqualTPlusTMinusTStarTSlashTNumberTIdentTIfTElseTWhileTReturn"

var _TKind_index = [...]uint8{0, 4, 12, 23, 33, 44, 54, 65, 69, 75, 85, 90, 96, 107, 117, 122, 132, 140, 153, 158, 164, 169, 175, 182, 188, 191, 196, 202, 209}

func (i TKind) String() string {
	i -= 1
	if i < 0 || i >= TKind(len(_TKind_index)-1) {
		return "TKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TKind_name[_TKind_index[i]:_TKind_index[i+1]]
}
