// Code generated by "stringer -type=TKind"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TComment-1]
	_ = x[TEOF-2]
	_ = x[TParenOpen-3]
	_ = x[TParenClose-4]
	_ = x[TBraceOpen-5]
	_ = x[TBraceClose-6]
	_ = x[TDot-7]
	_ = x[TComma-8]
	_ = x[TSemicolon-9]
	_ = x[TBang-10]
	_ = x[TEqual-11]
	_ = x[TEqualEqual-12]
	_ = x[TBangEqual-13]
	_ = x[TLess-14]
	_ = x[TLessEqual-15]
	_ = x[TGreater-16]
	_ = x[TGreaterEqual-17]
	_ = x[TPlus-18]
	_ = x[TMinus-19]
	_ = x[TStar-20]
	_ = x[TSlash-21]
	_ = x[TNumber-22]
	_ = x[TIdent-23]
	_ = x[TIf-24]
	_ = x[TElse-25]
	_ = x[TWhile-26]
	_ = x[TReturn-27]
}

const _TKind_name = "TCommentTEOFTParenOpenTParenCloseTBraceOpenTBraceCloseTDotTCommaTSemicolonTBangTEqualTEqualEqualTBangEqualTLessTLessEqualTGreaterTGreaterEqualTPlusTMinusTStarTSlashTNumberTIdentTIfTElseTWhileTReturn"

var _TKind_index = [...]uint8{0, 8, 12, 22, 33, 43, 54, 58, 64, 74, 79, 85, 96, 106, 111, 121, 129, 142, 147, 153, 158, 164, 171, 177, 180, 185, 191, 198}

func (i TKind) String() string {
	i -= 1
	if i < 0 || i >= TKind(len(_TKind_index)-1) {
		return "TKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TKind_name[_TKind_index[i]:_TKind_index[i+1]]
}
