// Code generated by goyacc grammar.y. DO NOT EDIT.

//line grammar.y:2
package parser

import __yyfmt__ "fmt"

//line grammar.y:2

import (
	"gazebo/ast"
)

//line grammar.y:9
type yySymType struct {
	yys           int
	Position      ast.Position
	Lexeme        string
	Expression    ast.Expression
	Expressions   []ast.Expression
	Statement     ast.Statement
	Statements    []ast.Statement
	FuncArguments []string
}

const DOT = 57346
const SEMICOLON = 57347
const COMMA = 57348
const COMMENT = 57349
const BRACE_OPEN = 57350
const BRACE_CLOSE = 57351
const PAREN_OPEN = 57352
const PAREN_CLOSE = 57353
const BRACKET_OPEN = 57354
const BRACKET_CLOSE = 57355
const PLUS = 57356
const MINUS = 57357
const STAR = 57358
const SLASH = 57359
const PERCENT = 57360
const EQUAL = 57361
const EQUAL_EQUAL = 57362
const BANG = 57363
const BANG_EQUAL = 57364
const LESS = 57365
const LESS_EQUAL = 57366
const GREATER = 57367
const GREATER_EQUAL = 57368
const NULL = 57369
const FALSE = 57370
const TRUE = 57371
const AND = 57372
const OR = 57373
const IF = 57374
const ELSE = 57375
const WHILE = 57376
const FUNC = 57377
const LAMBDA = 57378
const RETURN = 57379
const FLOAT = 57380
const INTEGER = 57381
const STRING = 57382
const IDENTIFIER = 57383

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DOT",
	"SEMICOLON",
	"COMMA",
	"COMMENT",
	"BRACE_OPEN",
	"BRACE_CLOSE",
	"PAREN_OPEN",
	"PAREN_CLOSE",
	"BRACKET_OPEN",
	"BRACKET_CLOSE",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"PERCENT",
	"EQUAL",
	"EQUAL_EQUAL",
	"BANG",
	"BANG_EQUAL",
	"LESS",
	"LESS_EQUAL",
	"GREATER",
	"GREATER_EQUAL",
	"NULL",
	"FALSE",
	"TRUE",
	"AND",
	"OR",
	"IF",
	"ELSE",
	"WHILE",
	"FUNC",
	"LAMBDA",
	"RETURN",
	"FLOAT",
	"INTEGER",
	"STRING",
	"IDENTIFIER",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar.y:199

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 154

var yyAct = [...]int8{
	3, 94, 26, 45, 24, 8, 4, 25, 18, 17,
	74, 39, 106, 95, 93, 47, 29, 51, 22, 98,
	96, 23, 28, 54, 55, 49, 52, 53, 40, 41,
	42, 39, 56, 20, 57, 21, 19, 37, 9, 38,
	43, 44, 15, 65, 66, 72, 75, 71, 40, 41,
	42, 45, 30, 76, 77, 73, 46, 37, 2, 38,
	43, 44, 48, 82, 83, 84, 85, 1, 89, 90,
	86, 87, 88, 78, 79, 92, 50, 97, 80, 81,
	70, 67, 68, 7, 101, 4, 69, 18, 17, 103,
	39, 58, 60, 59, 61, 29, 5, 101, 14, 104,
	100, 28, 102, 107, 108, 99, 105, 40, 41, 42,
	13, 12, 20, 11, 21, 19, 37, 9, 38, 43,
	44, 15, 39, 64, 63, 62, 10, 29, 6, 91,
	36, 35, 34, 28, 33, 32, 31, 27, 16, 40,
	41, 42, 0, 0, 0, 0, 0, 0, 37, 0,
	38, 43, 44, 48,
}

var yyPact = [...]int16{
	80, -1000, 80, -1000, -1000, 51, -1000, -1000, -1000, 112,
	-1000, -1000, -1000, -1000, -1000, 6, -1000, 80, -1000, -24,
	112, 112, -1000, -7, 12, 68, 107, 29, 21, 21,
	76, -1000, -1000, -1000, -1000, -1000, -1000, 37, -1000, 112,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 112,
	1, 36, 80, 80, 112, 112, 112, 112, 112, 112,
	112, 112, 112, 112, 112, 112, 112, 76, 76, 112,
	-27, -28, 9, -1000, -1000, -28, -14, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 94, -1000, -1000, 91, -1000, -1000, 78, 80, -1000,
	112, -29, 80, 80, -1000, -1000, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 5, 138, 18, 21, 4, 7, 2, 137, 52,
	136, 135, 134, 132, 131, 130, 129, 0, 128, 126,
	113, 111, 110, 98, 96, 83, 58, 1, 67,
}

var yyR1 = [...]int8{
	0, 28, 26, 26, 26, 17, 17, 17, 24, 24,
	24, 24, 25, 18, 18, 18, 18, 18, 19, 20,
	21, 27, 27, 27, 22, 22, 23, 1, 2, 3,
	3, 3, 4, 4, 4, 5, 5, 5, 5, 5,
	6, 6, 6, 6, 7, 7, 7, 8, 8, 8,
	9, 9, 9, 9, 9, 9, 9, 9, 16, 16,
	16, 10, 11, 12, 13, 13, 13, 13, 14, 15,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 0, 1, 2, 1, 1, 1,
	2, 1, 3, 1, 1, 1, 1, 1, 3, 1,
	6, 3, 1, 0, 5, 3, 3, 1, 1, 3,
	3, 1, 3, 3, 1, 3, 3, 3, 3, 1,
	3, 3, 3, 1, 3, 3, 1, 2, 2, 1,
	4, 3, 1, 1, 1, 1, 1, 1, 3, 1,
	0, 5, 1, 3, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -28, -26, -17, 5, -24, -18, -25, -1, 37,
	-19, -20, -21, -22, -23, 41, -2, 8, 7, 35,
	32, 34, -3, -4, -5, -6, -7, -8, 21, 15,
	-9, -10, -11, -12, -13, -14, -15, 36, 38, 10,
	27, 28, 29, 39, 40, -17, 5, -1, 41, 19,
	-26, 41, -1, -1, 30, 31, 20, 22, 23, 25,
	24, 26, 18, 17, 16, 14, 15, -9, -9, 10,
	4, 10, -1, -1, 9, 10, -17, -17, -3, -3,
	-4, -4, -5, -5, -5, -5, -6, -6, -6, -7,
	-7, -16, -1, 41, -27, 41, 11, -27, 33, 11,
	6, 6, 11, 11, -17, -1, 41, -17, -17,
}

var yyDef = [...]int8{
	4, -2, 1, 2, 5, 0, 7, 8, 9, 11,
	13, 14, 15, 16, 17, 64, 27, 4, 19, 0,
	0, 0, 28, 31, 34, 39, 43, 46, 0, 0,
	49, 52, 53, 54, 55, 56, 57, 0, 62, 0,
	65, 66, 67, 68, 69, 3, 6, 10, 64, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 47, 48, 60,
	0, 23, 0, 12, 18, 23, 25, 26, 29, 30,
	32, 33, 35, 36, 37, 38, 40, 41, 42, 44,
	45, 0, 59, 51, 0, 22, 63, 0, 0, 50,
	0, 0, 0, 0, 24, 58, 21, 61, 20,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:66
		{
			yylex.(*lexer).program.Statements = yyDollar[1].Statements
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:72
		{
			yyVAL.Statements = append(yyVAL.Statements, yyDollar[1].Statement)
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:73
		{
			yyVAL.Statements = append(yyVAL.Statements, yyDollar[2].Statement)
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:74
		{
			yyVAL.Statements = nil
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:78
		{
			yyVAL.Statement = &ast.Empty{Node: ast.Node{yyVAL.Position}}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:85
		{
			yyVAL.Statement = &ast.ExpressionStatement{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[1].Expression}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:86
		{
			yyVAL.Statement = &ast.Return{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[2].Expression}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:87
		{
			yyVAL.Statement = &ast.Return{Node: ast.Node{yyVAL.Position}}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:90
		{
			yyVAL.Statement = &ast.Assignment{Node: ast.Node{yyVAL.Position}, Identifier: yyDollar[1].Lexeme, Expression: yyDollar[3].Expression}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:100
		{
			yyVAL.Statement = &ast.Block{Node: ast.Node{yyVAL.Position}, Statements: yyDollar[2].Statements}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:102
		{
			yyVAL.Statement = &ast.Comment{Node: ast.Node{yyVAL.Position}, Text: yyDollar[1].Lexeme}
		}
	case 20:
		yyDollar = yyS[yypt-6 : yypt+1]
//line grammar.y:104
		{
			yyVAL.Statement = &ast.Func{Node: ast.Node{yyVAL.Position}, Name: yyDollar[2].Lexeme, Arguments: yyDollar[4].FuncArguments, Body: yyDollar[6].Statement}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:107
		{
			yyVAL.FuncArguments = append(yyVAL.FuncArguments, yyDollar[3].Lexeme)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:108
		{
			yyVAL.FuncArguments = append(yyVAL.FuncArguments, yyDollar[1].Lexeme)
		}
	case 23:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:109
		{
			yyVAL.FuncArguments = nil
		}
	case 24:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:113
		{
			yyVAL.Statement = &ast.If{Node: ast.Node{yyVAL.Position}, Condition: yyDollar[2].Expression, Body: yyDollar[3].Statement, Else: yyDollar[5].Statement}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:114
		{
			yyVAL.Statement = &ast.If{Node: ast.Node{yyVAL.Position}, Condition: yyDollar[2].Expression, Body: yyDollar[3].Statement}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:117
		{
			yyVAL.Statement = &ast.While{Node: ast.Node{yyVAL.Position}, Condition: yyDollar[2].Expression, Body: yyDollar[3].Statement}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:128
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpAnd, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:129
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpOr, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:134
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:135
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpNotEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:140
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpLess, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:141
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpGreater, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:142
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpLessOrEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:143
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpGreaterOrEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:148
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpModulus, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:149
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpDivide, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:150
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpMultiply, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:155
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpAdd, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:156
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpSubtract, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:161
		{
			yyVAL.Expression = &ast.Unary{Node: ast.Node{yyVAL.Position}, Op: ast.UnaryOpInvert, Right: yyDollar[2].Expression}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:162
		{
			yyVAL.Expression = &ast.Unary{Node: ast.Node{yyVAL.Position}, Op: ast.UnaryOpNegate, Right: yyDollar[2].Expression}
		}
	case 50:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:167
		{
			yyVAL.Expression = &ast.Call{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[1].Expression, Arguments: yyDollar[3].Expressions}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:168
		{
			yyVAL.Expression = &ast.GetAttribute{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[1].Expression, Name: yyDollar[3].Lexeme}
		}
	case 58:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:178
		{
			yyVAL.Expressions = append(yyVAL.Expressions, yyDollar[3].Expression)
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:179
		{
			yyVAL.Expressions = append(yyVAL.Expressions, yyDollar[1].Expression)
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:180
		{
			yyVAL.Expressions = nil
		}
	case 61:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:183
		{
			yyVAL.Expression = &ast.Lambda{Node: ast.Node{yyVAL.Position}, Arguments: yyDollar[3].FuncArguments, Body: yyDollar[5].Statement}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:185
		{
			yyVAL.Expression = &ast.Float{Node: ast.Node{yyVAL.Position}, Value: yyDollar[1].Lexeme}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:187
		{
			yyVAL.Expression = &ast.Group{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[2].Expression}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:190
		{
			yyVAL.Expression = &ast.Identifier{Node: ast.Node{yyVAL.Position}, Name: yyDollar[1].Lexeme}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:191
		{
			yyVAL.Expression = &ast.Null{Node: ast.Node{yyVAL.Position}}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:192
		{
			yyVAL.Expression = &ast.False{Node: ast.Node{yyVAL.Position}}
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:193
		{
			yyVAL.Expression = &ast.True{Node: ast.Node{yyVAL.Position}}
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:196
		{
			yyVAL.Expression = &ast.Integer{Node: ast.Node{yyVAL.Position}, Value: yyDollar[1].Lexeme}
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:198
		{
			yyVAL.Expression = &ast.String{Node: ast.Node{yyVAL.Position}, Value: yyDollar[1].Lexeme}
		}
	}
	goto yystack /* stack new state and value */
}
