// Code generated by goyacc grammar.y. DO NOT EDIT.

//line grammar.y:2
package parser

import __yyfmt__ "fmt"

//line grammar.y:2

import (
	"gazebo/ast"
)

//line grammar.y:9
type yySymType struct {
	yys         int
	Position    ast.Position
	Lexeme      string
	Expression  ast.Expression
	Expressions []ast.Expression
	Statement   ast.Statement
	Statements  []ast.Statement
}

const NEWLINE = 57346
const SEMICOLON = 57347
const COMMA = 57348
const COMMENT = 57349
const BRACE_OPEN = 57350
const BRACE_CLOSE = 57351
const PAREN_OPEN = 57352
const PAREN_CLOSE = 57353
const BRACKET_OPEN = 57354
const BRACKET_CLOSE = 57355
const PLUS = 57356
const MINUS = 57357
const STAR = 57358
const SLASH = 57359
const PERCENT = 57360
const EQUAL = 57361
const EQUAL_EQUAL = 57362
const BANG = 57363
const BANG_EQUAL = 57364
const LESS = 57365
const LESS_EQUAL = 57366
const GREATER = 57367
const GREATER_EQUAL = 57368
const NULL = 57369
const FALSE = 57370
const TRUE = 57371
const AND = 57372
const OR = 57373
const IF = 57374
const ELSE = 57375
const WHILE = 57376
const RETURN = 57377
const FLOAT = 57378
const INTEGER = 57379
const STRING = 57380
const IDENTIFIER = 57381

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NEWLINE",
	"SEMICOLON",
	"COMMA",
	"COMMENT",
	"BRACE_OPEN",
	"BRACE_CLOSE",
	"PAREN_OPEN",
	"PAREN_CLOSE",
	"BRACKET_OPEN",
	"BRACKET_CLOSE",
	"PLUS",
	"MINUS",
	"STAR",
	"SLASH",
	"PERCENT",
	"EQUAL",
	"EQUAL_EQUAL",
	"BANG",
	"BANG_EQUAL",
	"LESS",
	"LESS_EQUAL",
	"GREATER",
	"GREATER_EQUAL",
	"NULL",
	"FALSE",
	"TRUE",
	"AND",
	"OR",
	"IF",
	"ELSE",
	"WHILE",
	"RETURN",
	"FLOAT",
	"INTEGER",
	"STRING",
	"IDENTIFIER",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line grammar.y:179

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 133

var yyAct = [...]int8{
	7, 3, 22, 20, 39, 18, 15, 14, 21, 33,
	83, 46, 47, 41, 25, 26, 82, 43, 45, 61,
	24, 48, 19, 49, 57, 58, 34, 35, 36, 40,
	1, 16, 6, 17, 62, 32, 37, 38, 12, 4,
	59, 60, 63, 2, 39, 65, 11, 66, 50, 52,
	51, 53, 67, 68, 71, 72, 73, 74, 42, 10,
	78, 79, 81, 75, 76, 77, 9, 15, 14, 64,
	33, 69, 70, 8, 5, 25, 80, 56, 55, 54,
	31, 24, 30, 29, 28, 86, 87, 34, 35, 36,
	33, 27, 16, 23, 17, 25, 32, 37, 38, 12,
	85, 24, 13, 33, 0, 84, 0, 34, 35, 36,
	0, 0, 0, 0, 0, 0, 32, 37, 38, 44,
	34, 35, 36, 0, 0, 0, 0, 0, 0, 32,
	37, 38, 44,
}

var yyPact = [...]int16{
	-1, -1000, -1, -1000, 24, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -6, -1000, -1, -1000, 80, 80, -1000, -19,
	1, 25, 61, 10, 93, 93, 9, -1000, -1000, -1000,
	-1000, -1000, -1000, 80, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 80, 60, -1, -1000, -1, 80, 80, 80, 80,
	80, 80, 80, 80, 80, 80, 80, 80, 80, 9,
	9, 80, 5, -1000, -1000, -23, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	94, -1000, -1000, -1, -1000, 80, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 0, 102, 5, 22, 3, 8, 2, 93, 15,
	91, 84, 83, 82, 80, 76, 1, 74, 73, 66,
	59, 46, 39, 32, 43, 30,
}

var yyR1 = [...]int8{
	0, 25, 24, 24, 24, 16, 16, 22, 22, 23,
	17, 17, 17, 17, 18, 19, 20, 20, 21, 1,
	2, 3, 3, 3, 4, 4, 4, 5, 5, 5,
	5, 5, 6, 6, 6, 6, 7, 7, 7, 8,
	8, 8, 9, 9, 9, 9, 9, 9, 15, 15,
	15, 10, 11, 12, 12, 12, 12, 13, 14,
}

var yyR2 = [...]int8{
	0, 1, 1, 2, 0, 2, 1, 1, 1, 3,
	1, 1, 1, 1, 3, 1, 5, 3, 3, 1,
	1, 3, 3, 1, 3, 3, 1, 3, 3, 3,
	3, 1, 3, 3, 3, 1, 3, 3, 1, 2,
	2, 1, 4, 1, 1, 1, 1, 1, 1, 3,
	0, 1, 3, 1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -25, -24, -16, -22, -17, -23, -1, -18, -19,
	-20, -21, 39, -2, 8, 7, 32, 34, -3, -4,
	-5, -6, -7, -8, 21, 15, -9, -10, -11, -12,
	-13, -14, 36, 10, 27, 28, 29, 37, 38, -16,
	5, 19, -24, -1, 39, -1, 30, 31, 20, 22,
	23, 25, 24, 26, 18, 17, 16, 14, 15, -9,
	-9, 10, -1, -1, 9, -16, -16, -3, -3, -4,
	-4, -5, -5, -5, -5, -6, -6, -6, -7, -7,
	-15, -1, 11, 33, 11, 6, -16, -1,
}

var yyDef = [...]int8{
	4, -2, 1, 2, 0, 6, 7, 8, 10, 11,
	12, 13, 53, 19, 4, 15, 0, 0, 20, 23,
	26, 31, 35, 38, 0, 0, 41, 43, 44, 45,
	46, 47, 51, 0, 54, 55, 56, 57, 58, 3,
	5, 0, 0, 0, 53, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 39,
	40, 50, 0, 9, 14, 17, 18, 21, 22, 24,
	25, 27, 28, 29, 30, 32, 33, 34, 36, 37,
	0, 48, 52, 0, 42, 0, 16, 49,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:62
		{
			yylex.(*lexer).program.Statements = yyDollar[1].Statements
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:68
		{
			yyVAL.Statements = append(yyVAL.Statements, yyDollar[1].Statement)
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:69
		{
			yyVAL.Statements = append(yyVAL.Statements, yyDollar[2].Statement)
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:70
		{
			yyVAL.Statements = nil
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:80
		{
			yyVAL.Statement = &ast.ExpressionStatement{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[1].Expression}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:83
		{
			yyVAL.Statement = &ast.Assignment{Node: ast.Node{yyVAL.Position}, Identifier: yyDollar[1].Lexeme, Expression: yyDollar[3].Expression}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:92
		{
			yyVAL.Statement = &ast.Block{Node: ast.Node{yyVAL.Position}, Statements: yyDollar[2].Statements}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:94
		{
			yyVAL.Statement = &ast.Comment{Node: ast.Node{yyVAL.Position}, Text: yyDollar[1].Lexeme}
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line grammar.y:97
		{
			yyVAL.Statement = &ast.If{Node: ast.Node{yyVAL.Position}, Condition: yyDollar[2].Expression, Body: yyDollar[3].Statement, Else: yyDollar[5].Statement}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:98
		{
			yyVAL.Statement = &ast.If{Node: ast.Node{yyVAL.Position}, Condition: yyDollar[2].Expression, Body: yyDollar[3].Statement}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:101
		{
			yyVAL.Statement = &ast.While{Node: ast.Node{yyVAL.Position}, Condition: yyDollar[2].Expression, Body: yyDollar[3].Statement}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:112
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpAnd, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:113
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpOr, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:118
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:119
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpNotEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:124
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpLess, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:125
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpGreater, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:126
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpLessOrEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:127
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpGreaterOrEqual, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:132
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpModulus, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:133
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpDivide, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:134
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpMultiply, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:139
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpAdd, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:140
		{
			yyVAL.Expression = &ast.Binary{Node: ast.Node{yyVAL.Position}, Op: ast.BinaryOpSubtract, Left: yyDollar[1].Expression, Right: yyDollar[3].Expression}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:145
		{
			yyVAL.Expression = &ast.Unary{Node: ast.Node{yyVAL.Position}, Op: ast.UnaryOpInvert, Right: yyDollar[2].Expression}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line grammar.y:146
		{
			yyVAL.Expression = &ast.Unary{Node: ast.Node{yyVAL.Position}, Op: ast.UnaryOpNegate, Right: yyDollar[2].Expression}
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line grammar.y:151
		{
			yyVAL.Expression = &ast.Call{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[1].Expression, Arguments: yyDollar[3].Expressions}
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:160
		{
			yyVAL.Expressions = append(yyVAL.Expressions, yyDollar[1].Expression)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:161
		{
			yyVAL.Expressions = append(yyVAL.Expressions, yyDollar[3].Expression)
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line grammar.y:162
		{
			yyVAL.Expressions = nil
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:165
		{
			yyVAL.Expression = &ast.Float{Node: ast.Node{yyVAL.Position}, Value: yyDollar[1].Lexeme}
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line grammar.y:167
		{
			yyVAL.Expression = &ast.Group{Node: ast.Node{yyVAL.Position}, Expression: yyDollar[2].Expression}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:170
		{
			yyVAL.Expression = &ast.Identifier{Node: ast.Node{yyVAL.Position}, Name: yyDollar[1].Lexeme}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:171
		{
			yyVAL.Expression = &ast.Null{Node: ast.Node{yyVAL.Position}}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:172
		{
			yyVAL.Expression = &ast.False{Node: ast.Node{yyVAL.Position}}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:173
		{
			yyVAL.Expression = &ast.True{Node: ast.Node{yyVAL.Position}}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:176
		{
			yyVAL.Expression = &ast.Integer{Node: ast.Node{yyVAL.Position}, Value: yyDollar[1].Lexeme}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line grammar.y:178
		{
			yyVAL.Expression = &ast.String{Node: ast.Node{yyVAL.Position}, Value: yyDollar[1].Lexeme}
		}
	}
	goto yystack /* stack new state and value */
}
