// Code generated by "stringer -type=UnaryOp -output=ast/expr/unary_string.go ast/expr/unary.go"; DO NOT EDIT.

package expr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnaryNot-1]
	_ = x[UnaryPlus-2]
	_ = x[UnaryMinus-3]
}

const _UnaryOp_name = "UnaryNotUnaryPlusUnaryMinus"

var _UnaryOp_index = [...]uint8{0, 8, 17, 27}

func (i UnaryOp) String() string {
	i -= 1
	if i < 0 || i >= UnaryOp(len(_UnaryOp_index)-1) {
		return "UnaryOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UnaryOp_name[_UnaryOp_index[i]:_UnaryOp_index[i+1]]
}
